/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package io.github.matiaskotlik.huskiehack2019;

import io.github.matiaskotlik.huskiehack2019.ai.SentimentAnalysis;
import org.nanohttpd.protocols.http.IHTTPSession;
import org.nanohttpd.protocols.http.NanoHTTPD;
import org.nanohttpd.protocols.http.request.Method;
import org.nanohttpd.protocols.http.response.Response;
import org.nanohttpd.protocols.http.response.Status;

import java.io.File;
import java.io.FileInputStream;
import java.io.FileNotFoundException;
import java.io.IOException;
import java.nio.charset.StandardCharsets;
import java.nio.file.Files;
import java.nio.file.Paths;
import java.util.HashMap;
import java.util.HashSet;
import java.util.Map;
import java.util.Set;
import java.util.UUID;
import java.util.regex.Matcher;
import java.util.regex.Pattern;

public class App extends NanoHTTPD {
	private Template loginTmp;
	private Template btnTmp;

	private ComplimentStorage complimentStorage;

	private Set<String> users;

	private SessionList sessionList;

	private SentimentAnalysis sentimentAnalysis;

	private static final Pattern STATIC_PATH_PATTERN = Pattern.compile("^/static/([a-zA-Z0-9\\.\\-]+)$");
	private static final String LOCAL_DOCS_PATH = "docs/static/";

	public App(int port) {
		super(port);

		sessionList = new SessionList();

		users = new HashSet<>();

		loginTmp = getTemplate("docs/index.html");
		btnTmp = getTemplate("docs/buttonpage.html");

		complimentStorage = new ComplimentStorage();

		sentimentAnalysis = new SentimentAnalysis();
		sentimentAnalysis.sentiment("asdf");
	}

	public Session getSession(IHTTPSession ihttpSession) {
		return sessionList.getSession(getSessionId(ihttpSession));
	}

	public String getSessionId(IHTTPSession ihttpSession) {
		String id = ihttpSession.getCookies().read("session");
		id = id == null ? UUID.randomUUID().toString() : id;
		setSessionId(ihttpSession, id);
		return id;
	}

	public void setSessionId(IHTTPSession ihttpSession, String id) {
		ihttpSession.getCookies().set("session", id, Integer.MAX_VALUE);
	}

	public Map<String, String> getSessionDataMap(Session session) {
		Map<String, String> map = new HashMap<>();
		if (session.getName() != null) {
			map.put("name", session.getName());
		}
		return map;
	}

	@Override
	public Response serve(IHTTPSession ihttpSession) {
		Method method = ihttpSession.getMethod();
		String uri = ihttpSession.getUri();

		if (method.equals(Method.POST)) {
			try {
				ihttpSession.parseBody(new HashMap<>());
			} catch (IOException e) {
				System.err.println("Could not parse body");
			} catch (ResponseException e) {
				System.err.println("ResponseException when trying to parse body");
			}
		}

		if (uri.equals("/")) {
			Session session = getSession(ihttpSession);
			if (session.getName() != null) {
				return ss(btnTmp.render(getSessionDataMap(session)));
			} else {
				return ss(loginTmp.render(getSessionDataMap(session)));
			}
		} else if (uri.equals("/signin")) {
			Session session = getSession(ihttpSession);
			String name = ihttpSession.getParms().get("name");
			session.setName(name);
			users.add(name);
			return redirect("/");
		} else if (uri.equals("/give")) {
			String name = ihttpSession.getParms().get("name");
			String compliment = ihttpSession.getParms().get("compliment");
			if (name != null && compliment != null) {
				if (users.contains(name)) {
					System.out.println("analyzing " + compliment);
					if (sentimentAnalysis.sentiment(compliment)) {
						complimentStorage.store(name, compliment);
						return ss("Your compliment was sent!");
					} else {
						return ss("Either your compliment is shit or our AI is, but either way, go fuck yourself.");
					}
				} else {
					return ss("That user does not exist. Maybe you spelled it wrong?");
				}
			}
		} else if (uri.equals("/get")) {
			String name = getSession(ihttpSession).getName();
			System.out.println("getting compliment for name: " + name);
			if (name != null) {
				String compliment = complimentStorage.get(name);
				return compliment == null ? ss("You have no compliments.") : ss(compliment);
			}
		} else if (uri.equals("/list")) {
			StringBuilder listBuilder = new StringBuilder().append("[");
			users.forEach(user -> listBuilder.append("\"").append(user).append("\","));
			return ss(listBuilder.substring(0, listBuilder.length() - 1) + "]");
		} else if (uri.startsWith("/static/")) {
			Matcher m = STATIC_PATH_PATTERN.matcher(uri);
			if (m.find()) {
				String name = m.group(1);
				if (name != null) {
					return FileResponse(LOCAL_DOCS_PATH + name);
				}
			}
		}
		return Response.newFixedLengthResponse("Error 404 File not Found");
	}

	public Response FileResponse(String path) {
		File file = new File(path);
		String mime = NanoHTTPD.getMimeTypeForFile(file.getName());
		FileInputStream fis;
		try {
			fis = new FileInputStream(file);
		} catch (FileNotFoundException e) {
			System.err.println("Requested file: " + file.getPath() + ", not found.");
			return Response.newFixedLengthResponse("File not Found");
		}
		return Response.newFixedLengthResponse(Status.OK, mime, fis, file.length());
	}

	public Response redirect(String uri) {
		return Response.newFixedLengthResponse("<script>window.location.replace(\"" + uri + "\");</script>");
	}

	public Response ss(String msg) {
		return Response.newFixedLengthResponse(msg);
	}

	public static void main(String[] args) {
		int port = 0;
		if (args.length == 1) {
			port = Integer.parseInt(args[0]);
		} else {
			port = 8080;
		}
		App app = new App(port);
		System.out.println("Starting server...");
		try {
			app.start(NanoHTTPD.SOCKET_READ_TIMEOUT, false);
		} catch (IOException e) {
			System.err.println("Couldn't start server.");
			e.printStackTrace();
		}
	}

	public Template getTemplate(String path) {
		try {
			return new Template(getFile(path));
		} catch (IOException e) {
			System.err.println("Could not open file at path " + path);
			e.printStackTrace();
		}
		return new Template("Could not open file");
	}

	public String getFile(String path) throws IOException {
		return new String(Files.readAllBytes(Paths.get(path)), StandardCharsets.UTF_8);
	}
}
