/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package io.github.matiaskotlik.huskiehack2019;

import org.junit.Test;
import static org.junit.Assert.*;

import java.util.ArrayList;
import java.util.Scanner;

public class AppTest {
    @Test public void testAppHasAGreeting() {
        System.out.println("hi");
    }




}
