/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package io.github.matiaskotlik.huskiehack2019;

import io.github.matiaskotlik.huskiehack2019.cryptography.Hasher;
import org.junit.Test;

public class AppTest {
	@Test
	public void testComplimentStorage() {
		Hasher hasher = new Hasher();
		assert hasher.verify("1234", hasher.hash("1234", "1234"), "1234");
	}
}
